// <auto-generated />
namespace E7PNN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210209NewJoinAcc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210209NewJoinAcc));
        
        string IMigrationMetadata.Id
        {
            get { return "202102090947027_20210209NewJoinAcc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
