// <auto-generated />
namespace E7PNN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210202FristModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210202FristModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202102020628481_20210202FristModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
