// <auto-generated />
namespace E7PNN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20210306DitFistkey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20210306DitFistkey));
        
        string IMigrationMetadata.Id
        {
            get { return "202103060728260_20210306DitFistkey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
